<?php
  require_once('Views/Partials/header.php');
?>
<?php
    require_once('Views/Partials/slider.php');
?>
<?php
  require_once('Views/Partials/content.php');
?>
<?php
  require_once('Views/Partials/footer.php');
?>
